# Generated by Django 5.1.4 on 2024-12-11 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_gamelog_year_released'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamelog',
            name='console',
            field=models.CharField(default='0000000', max_length=100),
        ),
        migrations.AddField(
            model_name='gamelog',
            name='want_to_play_degree',
            field=models.IntegerField(choices=[(1, 'Not Much'), (2, 'Some What'), (3, 'Wants To'), (4, 'Very Much')], default=1),
        ),
    ]
